""" This script is generated by chatgpt """

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Read the CSV file
df = pd.read_csv('reactor_transient.csv')

# Create figure with subplots
fig, axes = plt.subplots(3, 2, figsize=(15, 12))
fig.suptitle('Reactor Transient Analysis', fontsize=16, fontweight='bold')

# Plot 1: Power
ax1 = axes[0, 0]
ax1.plot(df['Time(s)'], df['Power(MW)'], 'b-', linewidth=2)
ax1.axvline(x=200, color='r', linestyle='--', alpha=0.7, label='Rod Insertion')
ax1.axvline(x=400, color='g', linestyle='--', alpha=0.7, label='Rod Withdrawal')
ax1.set_ylabel('Power (MW)')
ax1.set_xlabel('Time (s)')
ax1.legend()
ax1.grid(True, alpha=0.3)
ax1.set_title('Reactor Power')

# Plot 2: Reactivity
ax2 = axes[0, 1]
ax2.plot(df['Time(s)'], df['Rho(pcm)'], 'g-', linewidth=2)
ax2.axvline(x=200, color='r', linestyle='--', alpha=0.7)
ax2.axvline(x=400, color='g', linestyle='--', alpha=0.7)
ax2.set_ylabel('Reactivity (pcm)')
ax2.set_xlabel('Time (s)')
ax2.grid(True, alpha=0.3)
ax2.set_title('Reactivity')

# Plot 3: Main Temperatures
ax3 = axes[1, 0]
ax3.plot(df['Time(s)'], df['T_fuel(C)'], 'r-', linewidth=2, label='Fuel')
ax3.plot(df['Time(s)'], df['T_mod(C)'], 'b-', linewidth=2, label='Moderator')
ax3.plot(df['Time(s)'], df['T_hot(C)'], 'orange', linewidth=2, label='Hot Leg')
ax3.plot(df['Time(s)'], df['T_cold(C)'], 'purple', linewidth=2, label='Cold Leg')
ax3.axvline(x=200, color='r', linestyle='--', alpha=0.7)
ax3.axvline(x=400, color='g', linestyle='--', alpha=0.7)
ax3.set_ylabel('Temperature (°C)')
ax3.set_xlabel('Time (s)')
ax3.legend(loc='best')
ax3.grid(True, alpha=0.3)
ax3.set_title('Primary System Temperatures')

# Plot 4: Plenum Temperatures
ax4 = axes[1, 1]
ax4.plot(df['Time(s)'], df['T_up(C)'], 'c-', linewidth=2, label='Upper Plenum')
ax4.plot(df['Time(s)'], df['T_lp(C)'], 'm-', linewidth=2, label='Lower Plenum')
ax4.axvline(x=200, color='r', linestyle='--', alpha=0.7)
ax4.axvline(x=400, color='g', linestyle='--', alpha=0.7)
ax4.set_ylabel('Temperature (°C)')
ax4.set_xlabel('Time (s)')
ax4.legend(loc='best')
ax4.grid(True, alpha=0.3)
ax4.set_title('Plenum Temperatures')

# Plot 5: Fuel Node Temperatures
ax5 = axes[2, 0]
fuel_columns = [col for col in df.columns if 'Fuel_Node' in col]
for col in fuel_columns:
    ax5.plot(df['Time(s)'], df[col], linewidth=2, label=col)
ax5.axvline(x=200, color='r', linestyle='--', alpha=0.7)
ax5.axvline(x=400, color='g', linestyle='--', alpha=0.7)
ax5.set_ylabel('Temperature (°C)')
ax5.set_xlabel('Time (s)')
ax5.legend(loc='best')
ax5.grid(True, alpha=0.3)
ax5.set_title('Fuel Node Temperatures')

# Plot 6: Coolant Node Temperatures
ax6 = axes[2, 1]
coolant_columns = [col for col in df.columns if 'Coolant_Node' in col]
for col in coolant_columns:
    ax6.plot(df['Time(s)'], df[col], linewidth=2, label=col)
ax6.axvline(x=200, color='r', linestyle='--', alpha=0.7)
ax6.axvline(x=400, color='g', linestyle='--', alpha=0.7)
ax6.set_ylabel('Temperature (°C)')
ax6.set_xlabel('Time (s)')
ax6.legend(loc='best', ncol=2)
ax6.grid(True, alpha=0.3)
ax6.set_title('Coolant Node Temperatures')

plt.tight_layout()
plt.show()

# Print summary statistics
print("\n" + "="*60)
print("SUMMARY STATISTICS")
print("="*60)

print(f"\nInitial State (t=0s):")
print(f"  Power: {df['Power(MW)'].iloc[0]:.2f} MW")
print(f"  Fuel Temperature: {df['T_fuel(C)'].iloc[0]:.2f} °C")
print(f"  Moderator Temperature: {df['T_mod(C)'].iloc[0]:.2f} °C")

print(f"\nAfter Rod Insertion (t=400s):")
df_at_400 = df[df['Time(s)'] >= 400].iloc[0]
print(f"  Power: {df_at_400['Power(MW)']:.2f} MW")
print(f"  Fuel Temperature: {df_at_400['T_fuel(C)']:.2f} °C")
print(f"  Moderator Temperature: {df_at_400['T_mod(C)']:.2f} °C")

print(f"\nFinal State (t={df['Time(s)'].iloc[-1]:.1f}s):")
print(f"  Power: {df['Power(MW)'].iloc[-1]:.2f} MW")
print(f"  Fuel Temperature: {df['T_fuel(C)'].iloc[-1]:.2f} °C")
print(f"  Moderator Temperature: {df['T_mod(C)'].iloc[-1]:.2f} °C")
print(f"  Hot Leg Temperature: {df['T_hot(C)'].iloc[-1]:.2f} °C")
print(f"  Cold Leg Temperature: {df['T_cold(C)'].iloc[-1]:.2f} °C")
print(f"  Hot-Cold ΔT: {df['T_hot(C)'].iloc[-1] - df['T_cold(C)'].iloc[-1]:.2f} °C")