name: tauhid


on:
  workflow_dispatch:
  push:
    branches: [ main, cpp_kernel ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libopenmpi-dev openmpi-bin         
          sudo apt install -y cmake libgtest-dev
      - name: Checkout code
        uses: actions/checkout@v6

      - name: cool_prop
        shell: bash
        run: |
          cd  externals
          git submodule update --init --recursive

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          make -j 8

      - name: Run Tests
        shell: bash
        run: |
          cd build/tests
          ./test_state
          ./test_integrator
          ./test_units
          ./test_water
          ./test_controllers
          ./test_kinetics_analytical
          ./test_reactor_analytical
          ./test_pump_analytical
          ./test_pressurizer_analytical
          ./test_helical_sg_analytical
          ./test_sg_analytical
          ./test_primary_loop

      - name: Run examples
        shell: bash
        run: |
          cd build/examples
          ./reactivity_step_transient
          ./pump_trip
          ./pressurizer_heatup
          ./helical_sg_transient
